// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgfaubtjrgsjzcavjbbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZmF1YnRqcmdzanpjYXZqYmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzI4NzUsImV4cCI6MjA2ODM0ODg3NX0.eYTTUQr_xFrKqvZ-gY4Iyb18Cgve5lZntqVCAd_sz2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});